export const ERRORS = {
    NOT_OWNER: 'Ownable: caller is not the owner',
    NOT_EXISTS: 'Pair not exists',
    ADDRESS_ZERO: "Address zero",
    NO_PROFIT: "No profit",
    WRONG_CALLER: "Wrong caller",
    NOT_ALLOWED: "Not allowed",
    REENTRANCY: 'ReentrancyGuard: reentrant call',
    DUPLICATE: "Duplicate",
    NOT_CONTRACT: "Not contract",
    NOT_ENOUGH_START_COLLATERAL: "Not enough collateral",
    AMOUNT_OUT_TOO_LOW: 'Amount out too low',
    INVALID_LEN: "Invalid len",
    ZERO_ADDRESS: "Zero address",
    INVALID_SINGLE_PATH: "Invalid path",
    INCONSISTENT_ROUTE: "Inconsistent route",
    NO_ROLE: (acc: string = "", role: string = "") => `AccessControl: account ${acc} is missing role ${role}`,
    NOT_EXECUTOR: 'Not executor',
    INIT_LOCKED: 'Initializable: contract is already initialized',
    NOTHING_TO_CLAIM: "Nothing to claim",
}